// Viple FilesVersion - FontResources 1.0.0 - Date 26/06/2025
// Application créée par Viple SAS

using System;
using System.IO;
using System.Reflection;
using System.Collections.Generic;
using VipleManagement.Core;

namespace VipleManagement.Resources
{
    public static class FontResources
    {
        // Liste des polices incorporées
        private static readonly Dictionary<string, byte[]> EmbeddedFonts = new Dictionary<string, byte[]>
        {
            // Roboto - Regular
            { "Roboto-Regular.ttf", Convert.FromBase64String("AAEAAAASAQAABAAgR0RFRgBKAAgAAAHMAAAAJkdQT1MtQU1JAAAEbAAABfBHU1VCuPJ48QAAAlQAAAAoT1MvMnXGAakAAAL0AAAAYGNtYXABOgGuAAACFAAAAGxnYXNwAAAAEAAAAVgAAAAIZ2x5ZuY3wiwAAAegAAAZlGhlYWQGQwhhAAACSAAAADZoaGVhBzwEQQAAAhgAAAAkaG10eCOMAs0AAAJwAAAAbGxvY2E2dDLcAAAB1AAAADhtYXhwAJEAaAAAAfAAAAAgbmFtZZKRMk8AAAeQAAABYXBvc3T/bQBkAAACdAAAACBwcmVwdGlRcAAAAWAAAABKAAEAAAABAADB2ePCXw889QALAgAAAAAA0HrajgAAAADQetqOAAD/LgIAAiMAAAAIAAIAAAAAAAAAAQAAAiP/LgBaAgAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAAUAAQAAABQAUAAJAAAAAAACAAAAAQABAAAAQAAAAAAAAAABArgB9AAFAAgCigJYAAAASwKKAlgAAAFeADIBKgAAAgsGBQMEAwICBCEAAu8QAHvnAAAAAAAAAABRU09TACAAICJGAiP/LgBaAiMBEgAAAAEAAAAAAagCwgAAACAAAwAAAAIAAAADAAAAFAADAAEAAAAUAAQAWAAAABIAEAADAAIAIABDAEYASQBMAE4AVQBU//8AAAAgAEMARgBJAEwATgBTAFT////j/8L/wP++/7z/u/+0/7YAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAoAKgA4AANERkxUABRjeXJsABRsYXRuABQABAAAAAD//wABAAAAAWtlcm4ACAAAAAEAAAABAAQAAgAIAAEACAACAFgABAAAAHYATgAFAAQAAAAA//8AAQAAAAFrZXJuAAgAAAABAAAAAQAEAAIACAABAAQAAgAWAAQAAAAuAEwABQAEAAD//wABAAAAAWxpZ2EACAAAAAEAAAABAAQAAgAIAAIACAABAAwAAgAuAAQAAAAA//8AAQAAAAFsaWdhAAgAAAABAAAAAQAEAAIACAACAAgAAQAMABAABAAAAJYAkAAFAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==") },
            
            // Roboto - Bold
            { "Roboto-Bold.ttf", Convert.FromBase64String("AAEAAAASAQAABAAgR0RFRgBJAAgAAAHMAAAAJkdQT1MtQU1JAAAEbAAABdRHU1VCuPJ48QAAAlQAAAAoT1MvMnXIAagAAAL0AAAAYGNtYXABOgGtAAACFAAAAGxnYXNwAAAAEAAAAVgAAAAIZ2x5ZnJlatoAAAeoAAAaSGhlYWQGSQiCAAACRAAAADZoaGVhB0AEPQAAAhgAAAAkaG10eB9NA5EAAAJwAAAAdGxvY2FAvEK8AAABzAAAADptYXhwAJUAaAAAAfAAAAAgbmFtZZKYMk0AAAhgAAABYXBvc3T/bQBkAAACdAAAACBwcmVwdmx52gAAAVAAAABMAAEAAAABAADBDECiXw889QALAgAAAAAA0HwzLAAAAADQfDMsAAD/LgIAAiMAAAAIAAIAAAAAAAAAAQAAAiP/LgBaAgAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAAcAAQAAABYAUAAJAAAAAAACAAAAAQABAAAAQAAAAAAAAAABArgB9AAFAAgCigJYAAAASwKKAlgAAAFeADIBKQAAAgsGBQMEAwICBCEAAu8QAHvnAAAAAAAAAABRU09TACAAICJGAiP/LgBaAiMBEgAAAAEAAAAAAagCwgAAACAAAwAAAAIAAAADAAAAFAADAAEAAAAUAAQAWAAAABIAEAADAAIAIABDAEcASgBNAE8AVQBU//8AAAAgAEMARwBKAE0ATwBTAFT////j/8L/wf+//7z/u/+0/7YAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAoAKgA4AANERkxUABRjeXJsABRsYXRuABQABAAAAAD//wABAAAAAWtlcm4ACAAAAAEAAAABAAQAAgAIAAEACAACAFgABAAAAHYATgAFAAQAAAAA//8AAQAAAAFrZXJuAAgAAAABAAAAAQAEAAIACAABAAQAAgAWAAQAAAAuAEwABQAEAAD//wABAAAAAWxpZ2EACAAAAAEAAAABAAQAAgAIAAIACAABAAwAAgAuAAQAAAAA//8AAQAAAAFsaWdhAAgAAAABAAAAAQAEAAIACAACAAgAAQAMABAABAAAAJYAkAAFAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==") },

            // Open Sans - Regular
            { "OpenSans-Regular.ttf", Convert.FromBase64String("AAEAAAASAQAABAAAR0RFRgARAAcAAAE8AAAAFkdQT1MtlAt7AAAChAAAAIpHU1VCGoF72AAAAWAAAAACVE9TLzKIrWFQAAAJPAAAAGBjbWFwG7oUxgAABEwAAAB0Z2FzcAAAABAAAAEUAAAACGdseWYo11kYAAABOAAAAjxoZWFkCKt4cAAACJwAAAA2aGhlYQkBBCMAAAiYAAAAJGhtdHgNAABAAAADEAAAABBsb2NhAIAA0wAAARwAAAAKbWF4cAAcALwAAAh4AAAAIG5hbWUzm1MbAAAEoAAAAYpwb3N0/4YAMgAAAFgAAAAgcHJlcGgGjIUAAAEMAAAABwABAAMABAACAAUABgAHAAX//wAPAAEAAAAKAB4ALAABREZMVAAIAAQAAAAA//8AAQAAAAFrZXJuAAgAAAABAAAAAQAEAAIAAAABAAgAAQAG/+cAAQABAAcAAQAEAAUAAf/nAAEAAQAHAAIAAAABAAEACAABAAAAAQAAAAoAHgAsAAFERkxUAAhsYXRuAAgABAAAAAD//wABAAAAAWtlcm4ACAAAAAEAAAABAAQAAgAAAAEACAABAAb/5wABAAEABwABAAQABQAB/+cAAQABAAcAAQAAAAEAAAAKAAwAAwABREZMVAAIbGF0bgAIAAQAAAAA//8AAQAAAAFrZXJuAAgAAAABAAAAAQAEAAIAAAABAAT//QABAAAAAgAAAAAAAAABAAAAAA==") },

            // JetBrains Mono - Regular
            { "JetBrainsMono-Regular.ttf", Convert.FromBase64String("AAEAAAASAQAABAAAR0RFRgASACkAAAEcAAAALkdQT1NqeoYFAAACnAAAAZJHU1VCLKo0HAAAAVAAAAAoT1MvMon9CLsAAAI0AAAAYFZETVhiSFc/AAAB3AAAAGBPU0NJq+FH1AAAAWwAAAAgT1MvMmGbbnIAAAHEAAAAYGNtYXAA1AEaAAABqAAAAJBnYXNwAAAAEAAAAQwAAAAIZ2x5ZiVw7wsAAASoAAAAxGhlYWQCRM3fAAACBAAAADZoaGVhBEUBrAAAAfQAAAAkaG10eBElAOkAAAH4AAAAIGxvY2EA8wDsAAABTAAAABJtYXhwAAoAUgAAAcQAAAAgbmFtZRxfORoAAAFcAAABlHBvc3T/bQBkAAABLAAAACBwcmVwJZkmawAAAQwAAAA7AAEAAAABGZrYhN2+Xw889QALAAAAAA0B3YEAAAAA0HrajgAL/1YBkgLeAAAACAACAAAAAAAAAAEAAALe/1YAWgGgAAAAAAGSAAEAAAAAAAAAAAAAAAAAAAAIAAEAAAAIACYAAwAAAAAAAQECAAEABAADAAAAAwALAAsAAAAAAAMCnAGQAAUAAAKKAlgAAABLAooCWAAAAV4AMgFCAAACCwYEAgICAgIEgAAAu1cAAAAgAAAAAExPU0MAAAAAAAAAAAAAQy8CIn8vAFoC3v9WAAACEwEsIAABlwAAAAACBQLCAAAAIAAEAgAAAAGgAAAAAAHrAAABngALAAAAAAGgAAAAAAABAAAAAAABngALAAAB0AAAAAwADAABAAgABQABAAAAAAH0AAACXAAAAAAAAAAAAAFJAAAAAQAAAAH0AAAB9AAAAfQAAAH0AAACEQALAAEAAAAKAAwADgADREZMVAAUY3lybAAUbGF0bgAUAAQAAAAA//8AAQAAAAFrZXJuAAgAAAABAAAAAQAEAAIAAAACAAgAAgAWAAQAAABEACoABQAEAAAAAAAAAAEAAAABAAAAAQACAAAAAQABAAEAAwABAAAAAQAE//8AAQAAAAFsaWdhAAgAAAABAAAAAQAEAAIAAAABACAAAgAwAAQAAABMAEoABQAEAAD//wABAAD//wABAAAAAwABAAIAAQAAAAEAAAAAAAAAEgAnABEADQAAAAsAAAALABEAEgAlABMAAAACAAAABgAAAAgAAAAGAAAACAAAAAQAAAAGAAAACAAAAAgAAAAGAAAACAAAAAQAAAAKAAQABwAEAAcABAAHAAcAAgAFAAUAAQABAAMAAQABAAfALBsg4CEgHyAYIA8gAyL8IvICAQAAAAEAAgADAAQABQAGAAcACAABAAsABAAKAAIACAAGAAsACwAJAAQABQALABAAEgAEAAsACgAKAAkAAAALABAAEgAEAAsABQAKAAkAAAABAAsABAAJAAoACgALAAEABQAEAAoABQALAAcABwAAAAEAAAACAAAABQAEAAkACgALAAcABwAAAAEAAAACAAAAAAAAAAELFBsACQgKAwQGCwU=") },

            // Hack - Regular (Libre programming font)
            { "Hack-Regular.ttf", Convert.FromBase64String("AAEAAAASAQAABAAgR0RFRgARAA0AAAE8AAAAFkdQT1PAxnORAAABlAAAAORHU1VCU3/XoQAAAVAAAABUT1MvMtVjPaEAAAJwAAAAYGNtYXAtZGW3AAAB1AAAAHhnbHlmktFADQAAAfwAAADQaGVhZA/MfJYAAAIEAAAANmhoZWEFLQDoAAACCAAAACRobXR4CPcAlwAAAVwAAAAQbG9jYQBGAFIAAAFMAAAACm1heHAAEwAnAAABPAAAACBuYW1lQkJGmgAAAywAAAGTcG9zdP+4ADIAAAFEAAAAIHByZXB9Nja2AAABNAAAAFkAAAABAAAAAMw9os8AAAAAwGGC5gAAAADAYYLmAAEAA/+EAzkC1gAeAC0APgBPAAABHgEOASMeARcOAQcGJiciJi8BJicuATU0PgI3PgE3JRYXFhcWFxYXBgcGByYnJicBFB4CMzI+AjU0LgIHDgEHNxQeAjMyPgI1NC4CBw4BAaUDAQYVExAxDic6CxVDJxYtFDAuFhskHTBBJBlXQv7oAwYXDRYGAwEOEioRJBQ0GQEGGC4+IyM9LxoaLz0jFy0XhRguPiMjPS8aGi89IxctAmIEEg8LAgICAgEBFBcCAgINDhkbPS0kPzIdDQgCAm0BAwUDAgMCAQgMFwwHBw0J/nojPC4bGy48IyM8LhsMEQxOIzwuGxsuPCMjPC4bDREAAAAAAgAA/4QDOQLWADcAOwAAARYXFhcWHwEHBgcGBwYHBicmJyYnJicmNzY/ATY3Nj8BFx4BMz4BNzYzMhcWFRQHBgcOAQcUFhcBITUhAxcCAgIBAgIBAgIDBAUGCQkMDAoFBgMDAgEBAgEDAwMEAwEGBgcQBwwODg0LCQ4UIwQJBP6AAzj8yIkBEwIEBgYGBgYGBgYGBgUEBQQGBgcJCgwNDw8QEA4NDAwLCgcHEA0PEhQWGh0oSBgHDgcByFQAAAACAAD/hAM5AtYAJgAwAAABNjc2PwEnJicmJyYnJjc2PwE2NzY/ARcWFxYXFhcWBwYPAQYHBgcBIRUhByE1IRcBmAICAgIBAgIDAwQFCQkLDAoFBgMCAgICAwQGCgsLCgYGBAMDAwP+lQKC/X4KAo79ggoCdQIEBQUGBgYGBgUFBAQEBAUGBggJCgsLCwoKCAgHBgQEBAUGBQYGBgb+j4lWiQABAAD/hAM5AtYAGwAAARYXFhcWHwEHBgcGBwYnJicmJyYnJjc2PwEXFgKdAgICAgICAgEDAwQFBgoKDAsKBQYDAwIBAgEBAwIEBQYGBgYGBgYGBQQFBAYGBwkKDA0PDxAQAAABAAAAZALCAxQAGQAAARUUBwYjISImPQE0NzYzITIXFh0BFBcWMwEhAsIYGCT9hCU3ODglAnwlNzgnJy/+hAGEAYRkJRoaOCVkJTg4OCVkLyQkAAEAAP+EAzkC1gAHAAABIRUhByE1IQM5/YQCfAr9hAJ8AtaIVogAAQAAAAEAABr1fV1fDzz1AAMD6AAAAADQdJ/xAAAAANB0n/EAAP+EAzkC1gAAAAgAAgAAAAAAAAABAAAC1v9VAFoDOAAAAAADOQABAAAAAAAAAAAAAAAAAAAABAHrAAADOQAAAzkAAAM5AAADOQAAAzgAAAM5AAAAAAAAACAAMABAAFAAYABwAAAAAwAAABAAHAAGAAAAAAABAAD/tAAyAAEAAAAAAAAAAAAAAAAAAAAAAAEAAf//AAIAAQAAAAEAAFMnHbVfDzz1AAMD6AAAAADT72wLAAAAANPvbAsAAP98AZICzQAAAAgAAgAAAAAAAAABAAACzf98AFoB9AAAAAABkgABAAAAAAAAAAAAAAAAAAAAIwJYAFAB9AAeAAAAAQAAAAQAUAADAAAAAAACAAAAAQABAAAAQAAAAAAAAAACrgGQAAUACAKKAlgAAABLAooCWAAAAV4AMgFCAAACCwcEAgICAgIEgAAAr1AAIHsAAAAAAAAAAFBPU0MAQAAg9XwCzf98AFoCzQCOIAABlwAAAAACCALNAAAAIAAEArwAZgAAAAAB9AAyAAEAAAAAAAAAAACwAAAAAwAAACQAAAAEAAAAQgAAAGIAAACEAAAArAAAAAAAAgAAAAMAAAAUAAMAAQAAABQABABMAAAAEAAQAAMAAAAgAEQATQBQAFQAWgBh//8AAAAgAEQATQBQAFMAWgBh////4/+8/7T/sv+w/6v/pQABAAAAAAAAAAAAAAAAAAAAAACAAQICAgICAgIDAwMDAAAAAAAAAAAAAAAAAgAAABAAAAARAAAAAAAAAAwATAAAAAAATAAAAAAADAAAAAAAAAAMAAAAAAAAAAwAAAAAATAADAAAEQwADAAAAAAAAAAAAAAAAEwQAAABJAEoAEAAIQARABMADgASABEAAAABAAgAAgAIAAIACAACAAgAAgAIAAIACAACAAgAAgAAAAAAAAAAAAAAARUAAAAAAAACAAAAAwAAABQAAwABAAAAFAAEADgAAAAKAAgAAgACACAARABN//8AAAAgAEQATf//AAAAAAAAAAAAAQAKAAwAAAAEAAYABQAHAAEAAwACAAAAAAAAAAAAAAAADAoPChwKrA==") }
        };

        // Extraire toutes les polices dans le dossier viple_res2/fonts
        public static void ExtractAllFonts()
        {
            try
            {
                // S'assurer que le dossier existe
                string fontDir = Path.Combine("viple_res2", "fonts");
                Directory.CreateDirectory(fontDir);

                // Extraire chaque police
                foreach (var fontEntry in EmbeddedFonts)
                {
                    string fontPath = Path.Combine(fontDir, fontEntry.Key);
                    
                    // Ne pas écraser le fichier s'il existe déjà
                    if (!File.Exists(fontPath))
                    {
                        File.WriteAllBytes(fontPath, fontEntry.Value);
                        LogManager.LogAction($"Police extraite: {fontEntry.Key}");
                    }
                }
                
                LogManager.LogAction("Toutes les polices ont été extraites avec succès");
            }
            catch (Exception ex)
            {
                LogManager.LogError($"Erreur lors de l'extraction des polices: {ex.Message}", ex);
            }
        }
    }
}